#load_module /usr/share/nginx/modules/ngx_http_image_filter_module.so;

events {}

user root;
http{
	include /etc/nginx/mime.types;
	
	server{
		listen 443 ssl;
		server_name 127.0.0.1 192.168.0.8 linux;
		index index.html index.htm;


		ssl_certificate /home/curso-nginx/proxy-reverso/https/server.crt;
		ssl_certificate_key /home/curso-nginx/proxy-reverso/https/server.key;
		
        location / {
			default_type text/html;
			return 200 "<!DOCTYPE html><h2>Hello World with HTTPS</h2>\n";
		}


		# location / {
		# 	proxy_pass http://127.0.0.1:8000;
		# 	proxy_set_header Host $host;
		# 	proxy_set_header X-Forwarded-Proto https;
		# }
	}

	server{
		listen 8000;
		server_name 127.0.0.1 linux;
		index index.html index.htm;
		root /home/curso-nginx/proxy-reverso/https;
	}
}