load_module /usr/share/nginx/modules/ngx_http_image_filter_module.so;

events {}

user root;
http{
	include /etc/nginx/mime.types;
	
	server{
		listen 8000;
		server_name 127.0.0.1 linux;
		root /home/curso-nginx/galeria-fotos/;
		index index.html index.htm;

		# NO-CACHE
		# o cache do navegador é DESABILITADO
		location ~ "^/no-cache/(?<image>.+)$" {
			alias /home/curso-nginx/galeria-fotos/$image;
			add_header Last-Modified $date_gmt;
		 	add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
		}

		# CACHE
		# o cache do navegador é HABILITADO
		location ~ "^/cache/(?<image>.+)$" {
			alias /home/curso-nginx/galeria-fotos/$image;
			add_header Last-Modified $date_gmt;
		 	add_header Cache-Control public;
			#expires 5m;
			expires @23h59m;
		}
	
		# THUMBNAIL
		# Gera uma miniatura da imagem, com 90% de qualidade
		location ~ "^/thumbnail/(?P<width>[0-9]+)/(?<image>.+)$" {
			alias /home/curso-nginx/galeria-fotos/$image;
			image_filter resize $width -;
			image_filter_jpeg_quality 90;

			image_filter_buffer 20M; # Utiliza até 20MB de memória p/ carregar a imagem, antes de aplicar o resize.
		}

	    # THUMBNAIL + QUALIDADE
		location ~ "^/resize/(?P<quality>[0-9]+)/(?<image>.+\.jpg)$" {
			root /home/curso-nginx/galeria-fotos;
			rewrite ^/resize/[0-9]+/(.+)$ /$1 break;
			
			image_filter resize 1024 -;
			image_filter_jpeg_quality $quality;

			image_filter_buffer 20M;
		}

		# MEMORY CACHE
		# As imagens processadas ficam armazenadas em memória, evitando o acesso ao disco, utilizando o open_file_cache para armazenar as imagens processadas em memória, evitando o acesso ao disco.
		location ~ "^/memory-cache/(?<image>.+)$" {
			alias /home/curso-nginx/galeria-fotos/$image;
			open_file_cache max=1000 inactive=1h;
			open_file_cache_valid 1h;
			open_file_cache_min_uses 1;
			open_file_cache_errors on;

			# Pra confirmar que a imagem foi processada e armazenada em memória, verifique se a coluna "buff/cache" aumentou
			# $>free -m

			# limpe o cache
			# sudo sync
 			# echo 3 | sudo tee /proc/sys/vm/drop_caches

			# rode o comando free novamente para verificar que o cache foi limpo

		}

		# MEMORY CACHE (thumbnail)
		# Utiliza o proxy_cache, devido ao image_filter resize, para armazenar as NOVAS imagens thumb em memória, evitando o acesso ao disco.
		location "^~/memory-cache/thumb/" {
			proxy_pass http://localhost:8000/thumbnail/200/;
			proxy_cache imagem_memoria;
			proxy_cache_key $uri;
			proxy_cache_valid 200 1h;

			# abra o diretório /dev/shm/nginx-cache, e verifique se as imagens processadas estão sendo armazenadas em memória			
		}

		# CROP
		# Faz o recorte centralizado da imagem
		location ~ ^/crop/(?<w>\d+)/(?<h>\d+)/(?<image>.+)$ {
			alias /home/curso-nginx/galeria-fotos/$image;
			image_filter crop $w $h;
			image_filter_buffer 10M;
		}

		# SHARPEN
		# 
		location ~ ^/sharpen/(?<percent>\d+)/(?<image>.+)$ {
			alias /home/curso-nginx/galeria-fotos/$image;
			image_filter_transparency on;
			image_filter_buffer 10M;
		}


	}



    # MEMORY CACHE (thumbnail)
	# Configuração de memory-cache para armazenar as imagens processadas em memória, evitando o acesso ao disco.
	proxy_cache_path /dev/shm/nginx-cache
		levels=1:2
		keys_zone=imagem_memoria:200m
		max_size=200m
		inactive=1h
		use_temp_path=off;

	# FIX 415 unsupported media type (cache-em-memoria), devido ao image_filter, 
	# que precisa carregar a imagem em memória para processar o resize.
	# O buffer padrão é de 1MB, que é insuficiente para carregar as imagens maiores.
  	image_filter_buffer 10M;
}